use_dist: 1
use_product: 1
encoder_layers: 12
kernel_num: 16
embed_dim: 768
ffn_embed_dim: 3072
attention_heads: 8
emb_dropout: 0.1
dropout: 0.1
attention_dropout: 0.1
activation_dropout: 0.0
max_seq_len: 256